In [1]:
from datetime import datetime
from meteostat import Point, Daily

In [2]:
# Set time period
start = datetime(2015, 1, 1)
end = datetime(2023, 12, 31)

In [3]:
# Create Point for Ipanema, RJ - BR
dados = Point(-22.983174, -43.204868)

In [4]:
# Get daily data (01/2015 - 12/2023)
data = Daily(dados, start, end)
data = data.fetch()
data.head(20)

            tavg  tmin  tmax  prcp  snow   wdir  wspd  wpgt  pres  tsun
time
2015-07-01  24.1  21.0  28.0   NaN   NaN  292.0  11.8   NaN   NaN   NaN
2015-07-02  22.0  20.0  24.0   NaN   NaN  106.0   9.6   NaN   NaN   NaN
2015-07-03  22.6  21.0  25.0   NaN   NaN   20.0   5.9   NaN   NaN   NaN
2015-07-04  23.2  18.0  27.0   NaN   NaN  271.0  13.8   NaN   NaN   NaN
2015-07-05  18.3  17.0  20.0   NaN   NaN  240.0   7.9   NaN   NaN   NaN
2015-07-06  19.7  18.0  22.0   NaN   NaN   42.0   8.2   NaN   NaN   NaN
2015-07-07  21.6  19.0  25.0   NaN   NaN   78.0   6.9   NaN   NaN   NaN
2015-07-08  22.5  20.0  25.9   NaN   NaN  354.0   6.5   NaN   NaN   NaN
2015-07-09  23.4  21.0  28.0   NaN   NaN  248.0  11.0   NaN   NaN   NaN
2015-07-10  22.0  19.0  26.0   NaN   NaN   86.0   9.4   NaN   NaN   NaN
2015-07-11  22.4  20.0  26.0   NaN   NaN  186.0  10.7   NaN   NaN   NaN
2015-07-12  23.1  20.0  27.0   NaN   NaN   52.0   6.8   NaN   NaN   NaN
2015-07-13  24.4  21.0  28.0   NaN   NaN  333.0   8.2   NaN   NaN   NaN
2015-07-14  24.5  21.0  30.0   NaN   NaN  325.0   8.8   NaN   NaN   NaN
2015-07-15  22.5  21.0  26.0   NaN   NaN   42.0  10.3   NaN   NaN   NaN
2015-07-16  22.9  20.0  26.0   NaN   NaN   91.0   8.4   NaN   NaN   NaN
2015-07-17  22.6  20.0  26.0   NaN   NaN   34.0   9.1   NaN   NaN   NaN
2015-07-18  22.4  21.0  25.0   NaN   NaN   93.0  10.9   NaN   NaN   NaN
2015-07-19  23.0  20.0  27.0   NaN   NaN   99.0   8.4   NaN   NaN   NaN
2015-07-20  24.6  21.0  31.0   NaN   NaN  337.0   8.8   NaN   NaN   NaN